// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PersonRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PersonRoot : GPBRootObject
@end

#pragma mark - AppContextMessage

typedef GPB_ENUM(AppContextMessage_FieldNumber) {
  AppContextMessage_FieldNumber_NetConnetionType = 1,
  AppContextMessage_FieldNumber_ScreenResolution = 2,
  AppContextMessage_FieldNumber_DeviceToken = 3,
  AppContextMessage_FieldNumber_MacAddress = 4,
  AppContextMessage_FieldNumber_CarrierName = 5,
  AppContextMessage_FieldNumber_DeviceModel = 6,
  AppContextMessage_FieldNumber_WifiName = 7,
  AppContextMessage_FieldNumber_DeviceName = 8,
  AppContextMessage_FieldNumber_DeviceType = 9,
  AppContextMessage_FieldNumber_SystemVersion = 10,
  AppContextMessage_FieldNumber_DeviceUuid = 11,
  AppContextMessage_FieldNumber_Gps = 12,
  AppContextMessage_FieldNumber_AppVersion = 13,
};

@interface AppContextMessage : GPBMessage

/** 网络连接类型,可选值是wifi/wwan/unknown */
@property(nonatomic, readwrite, copy, null_resettable) NSString *netConnetionType;
/** Test to see if @c netConnetionType has been set. */
@property(nonatomic, readwrite) BOOL hasNetConnetionType;

/** 屏幕分辨率 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *screenResolution;
/** Test to see if @c screenResolution has been set. */
@property(nonatomic, readwrite) BOOL hasScreenResolution;

/** 推送设备号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceToken;
/** Test to see if @c deviceToken has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceToken;

/** mac地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *macAddress;
/** Test to see if @c macAddress has been set. */
@property(nonatomic, readwrite) BOOL hasMacAddress;

/** 运营商名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *carrierName;
/** Test to see if @c carrierName has been set. */
@property(nonatomic, readwrite) BOOL hasCarrierName;

/** 设备型号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceModel;
/** Test to see if @c deviceModel has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceModel;

/** wifi名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *wifiName;
/** Test to see if @c wifiName has been set. */
@property(nonatomic, readwrite) BOOL hasWifiName;

/** 设备名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;
/** Test to see if @c deviceName has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceName;

/** 设备类型，可选值是iPhone/iPad/Android */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceType;
/** Test to see if @c deviceType has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceType;

/** 系统版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *systemVersion;
/** Test to see if @c systemVersion has been set. */
@property(nonatomic, readwrite) BOOL hasSystemVersion;

/** 设备号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceUuid;
/** Test to see if @c deviceUuid has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceUuid;

/** 经纬度(latitude,longitude) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gps;
/** Test to see if @c gps has been set. */
@property(nonatomic, readwrite) BOOL hasGps;

/** 当前安装的APP版本号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appVersion;
/** Test to see if @c appVersion has been set. */
@property(nonatomic, readwrite) BOOL hasAppVersion;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
